### PR TITLE
Making the README.md look nicer.

### PR DESCRIPTION
**Pull request by CoryG89**
I was able to make the image and link work on the README.md by changing the HTML to the simpler markdown format. 

Old HTML:

```
<a href="http://en.wikipedia.org/wiki/File:Jean_Auguste_Dominique_Ingres_019.jpg">
<img width="640" src="./node-romulus/raw/master/romulus.jpg">
</a>
```

New Markdown:

```
[![Romulus](romulus.jpg)](http://en.wikipedia.org/wiki/File:Jean_Auguste_Dominique_Ingres_019.jpg)
```

This looks like a great project that I'd like to contribute to in the future if I have the time, hoping to get it more attention by making the README look nicer.

### CODE REVIEW

**Comment by felixge** [comment]
@CoryG89 thx. Hotlinking is kinda bad, so it would be nicer to set the link to Github again. Anyway, added you as a collaborator, feel free to merge this one way or another.

btw. this used to work - github changed their urls ... : (

**Comment by CoryG89** [comment]
> @CoryG89 thx. Hotlinking is kinda bad, so it would be nicer to set the link to Github again. Anyway, added you as > a collaborator, feel free to merge this one way or another.

I think the markdown in my commit is pretty much the same as the HTML you had before. Here is what my markdown renders to:

```
<p><a href="http://en.wikipedia.org/wiki/File:Jean_Auguste_Dominique_Ingres_019.jpg"><img src="romulus.jpg" alt="Romulus" /></a></p>
```

The only difference is the p tags, and the alt text, which won't make a difference. This is not really an inline or 'hotlink' as the image is being pulled directly from `romulus.jpg` in the `master` branch. What we're doing is creating a regular (not hot) link to the original source image on Wikipedia, and the anchor just happens to contain our copy of the image. It would be hotlinking if we used the wikipedia image's link in the src attribute of the image, with or without the anchor.

> btw. this used to work - github changed their urls ... : (

Yeah I figured so. GitHub changed the way their links work in markdown to support [**relative linking**](https://github.com/blog/1395-relative-links-in-markup-files). Only downside is that it broke it for everyone doing it the other way.

Are you saying you don't want to link to Wikipedia? Would you rather link to the `romulus.jpg` file in your repo? If so I'll go ahead and do that and merge it in, otherwise I'll leave it as it is.

**Comment by CoryG89** [comment]
You're right though, I thought the problem at first was that GitHub was stripping out your HTML completely, however, this is just due to the relative linking issue, and simply changing the src in your HTML to `romulus.jpg` would have made it work as well.

**Comment by felixge** [comment]
Thx!

**Pull request merged**
